apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-product-delivery-deployment
  namespace: vehicle-lifecycle
  labels:
    app: data-product-delivery
spec:
  selector:
    matchLabels:
      app: data-product-delivery
  template:
    metadata:
      labels:
        app: data-product-delivery
        version: 2022-12-07-1048
    spec:
      serviceAccountName: data-product-delivery
      automountServiceAccountToken: false
      dnsConfig:
        nameservers:
          - 8.8.8.8
        options:
          - name: single-request-reopen
          - name: use-vc
      securityContext:
        fsGroup: 2000
      containers:
        - name: data-product-delivery
          image: nginx:latest
          securityContext:
              runAsUser: 1000
              runAsGroup: 3000
          env:
            - name: SERVER_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http

          livenessProbe:
            initialDelaySeconds: 80
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            initialDelaySeconds: 80
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 128Mi
