---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: data-product-delivery-service
  namespace: vehicle-lifecycle
spec:
  podSelector:
    matchLabels:
      app: data-product-delivery
  listeners:
    - portMapping:
        port: 8080
        protocol: http
      tls:
        mode: PERMISSIVE
        certificate:
          sds:
            secretName: spiffe://vcdp-developers/data-product-delivery-service
        validation:
          trust:
            sds:
              secretName: spiffe://vcdp-developers
          subjectAlternativeNames:
            match:
              exact:
              - spiffe://vcdp-developers/vlc-api-gateway-service
              - spiffe://vcdp-developers/vlc-data-product-manager-service

  serviceDiscovery:
    dns:
      hostname: data-product-delivery-service.vehicle-lifecycle.svc.cluster.local
  backends:
    - virtualService:
        virtualServiceRef:
          name: dv-state-handler-service
    - virtualService:
        virtualServiceRef:
          name: publisher-service
    - virtualService:
        virtualServiceRef:
          name: vlc-data-product-manager-service
  backendDefaults:
    clientPolicy:
      tls:
        enforce: false
        # certificate:
        #   sds:
        #     secretName: spiffe://vcdp-developers/data-product-delivery-service
        validation:
          trust:
            sds:
              secretName: spiffe://vcdp-developers
          subjectAlternativeNames:
            match:
              exact:
                - spiffe://vcdp-developers/dv-state-handler-service
                - spiffe://vcdp-developers/publisher-service
                - spiffe://vcdp-developers/vlc-data-product-manager-service

---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: vehicle-lifecycle
  name: data-product-delivery-service
spec:
  awsName: data-product-delivery-service
  listeners:
    - portMapping:
        port: 8080
        protocol: http
  routes:
    - name: default
      httpRoute:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: data-product-delivery-service
              weight: 100
        retryPolicy:
          maxRetries: 2
          perRetryTimeout:
            unit: ms
            value: 2000
          httpRetryEvents:
            - server-error
            - client-error
            - gateway-error
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: data-product-delivery-service
  namespace: vehicle-lifecycle
spec:
  awsName: data-product-delivery-service
  provider:
    virtualRouter:
      virtualRouterRef:
        name: data-product-delivery-service
