apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-product-delivery-deployment
  namespace: vehicle-lifecycle
spec:
  template:
    spec:
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: apmsocketpath
      containers:
        - name: data-product-delivery
          volumeMounts:
            - name: apmsocketpath
              mountPath: /var/run/datadog
