apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- ./deployment-environment-variables.yaml
- ./deployment-volumes.yaml
- ./deployment-server-port.yaml
- ./deployment-sa.yaml
images:
- name: 557068259488.dkr.ecr.eu-west-2.amazonaws.com/vlc-data-product-delivery
  newTag: 74cfbe8294be62dde738a73683e875113c8ad4c0
resources:
- ../base
- ./appmesh.yaml
