apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-product-delivery-deployment
  namespace: vehicle-lifecycle
  labels:
    app: data-product-delivery
    app.kubernetes.io/instance: data-product-delivery
spec:
  template:
    spec:
      containers:
        - name: data-product-delivery
          env:
            - name: SERVER_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http
