apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-product-delivery-deployment
  namespace: vehicle-lifecycle
  labels:
    app: data-product-delivery
    owner: Halo 
    project: vcdp-developers
spec:
  selector:
    matchLabels:
      app: data-product-delivery
  template:
    metadata:
      labels:
        app: data-product-delivery
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - name: data-product-delivery
          image: 557068259488.dkr.ecr.eu-west-2.amazonaws.com/vlc-data-product-delivery:latest
          securityContext:
              runAsUser: 1000
              runAsGroup: 3000
          env:
            - name: SERVER_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http

          livenessProbe:
            initialDelaySeconds: 80
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            initialDelaySeconds: 80
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 128Mi
