apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: data-product-delivery-hpa
  namespace: vehicle-lifecycle
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-product-delivery-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
