apiVersion: v1
kind: Service
metadata:
  name: data-product-delivery-service
  namespace: vehicle-lifecycle
spec:
  selector:
    app: data-product-delivery
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
